### ISSUE TITLE
Using attachment on incompatible weapon removes from inventory

### ISSUE THREAD

**Issue by Ventrix1994** [Gregorsaur/ESX-Easy-Weapon-Accessories#4]
Hi there.
example: You use a suppressor on a Heavy Revolver. It will tell you that it is not compatible but still remove it from your inventory anyway, and it's gone. Is there a fix so that if a weapon attachment isn't compatible it won't get used and stay in your inventory?

**Comment by frontoge** [comment]
Add the following on line 53 of the client/main.lua after the notification
`TriggerServerEvent('eden_accesories:giveBack', type)`
This should fix your issue. I would commit this to repo but I don't have push access.
