### ISSUE TITLE
Issue with Sql

### ISSUE THREAD

**Issue by Blaid9** [Gregorsaur/ESX-Easy-Weapon-Accessories#5]
Hello , when I try to import the sql file I've got this error : 

Erreur
Requête SQL : Copier

INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES
('yusuf', 'Weapon Skin', 1, 0, 1),
('grip', 'Grip', 1, 0, 1),
('flashlight', 'Flashlight', 1, 0, 1),
('suppressor', 'Suppressor', 1, 0, 1)
MySQL a répondu : Documentation

#1054 - Champ 'limit' inconnu dans field list

What sould I do ?

Thanks

**Comment by Gregorsaur** [comment]
You have a duplicate.
